// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_service_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRegisterRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterRequest) Reset()         { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()    {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *UserRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterRequest.Unmarshal(m, b)
}
func (m *UserRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterRequest.Marshal(b, m, deterministic)
}
func (m *UserRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterRequest.Merge(m, src)
}
func (m *UserRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegisterRequest.Size(m)
}
func (m *UserRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterRequest proto.InternalMessageInfo

func (m *UserRegisterRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserRegisterRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserRegisterRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type UserRegisterResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterResponse) Reset()         { *m = UserRegisterResponse{} }
func (m *UserRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*UserRegisterResponse) ProtoMessage()    {}
func (*UserRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *UserRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterResponse.Unmarshal(m, b)
}
func (m *UserRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterResponse.Marshal(b, m, deterministic)
}
func (m *UserRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterResponse.Merge(m, src)
}
func (m *UserRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_UserRegisterResponse.Size(m)
}
func (m *UserRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterResponse proto.InternalMessageInfo

func (m *UserRegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRegisterRequest)(nil), "go.micro.service.user.UserRegisterRequest")
	proto.RegisterType((*UserRegisterResponse)(nil), "go.micro.service.user.UserRegisterResponse")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0xca, 0xc2, 0x30,
	0x10, 0x84, 0xff, 0xfe, 0x15, 0x6d, 0xf7, 0x24, 0xd1, 0x42, 0x51, 0x04, 0xe9, 0x49, 0x14, 0xa2,
	0xe8, 0x7b, 0x78, 0x28, 0x78, 0x96, 0x5a, 0xd7, 0x92, 0x43, 0x9a, 0x9a, 0x4d, 0xf5, 0xf5, 0x25,
	0x5b, 0x7a, 0x10, 0x7a, 0xf0, 0x92, 0x64, 0xe7, 0xcb, 0x30, 0x93, 0x40, 0xd2, 0x58, 0xe3, 0xcc,
	0xbe, 0x25, 0xb4, 0xbc, 0x48, 0x9e, 0x45, 0x52, 0x19, 0xa9, 0x55, 0x69, 0x8d, 0x24, 0xb4, 0x2f,
	0x55, 0xa2, 0xf4, 0x30, 0x2b, 0x61, 0x76, 0x21, 0xb4, 0x39, 0x56, 0x8a, 0x9c, 0xdf, 0x9f, 0x2d,
	0x92, 0x13, 0x4b, 0x88, 0x3d, 0xbe, 0xd6, 0x85, 0xc6, 0x34, 0x58, 0x07, 0x9b, 0x38, 0x8f, 0xbc,
	0x70, 0x2e, 0x34, 0x8a, 0x15, 0xc0, 0x43, 0x59, 0x72, 0x1d, 0xfd, 0x67, 0x1a, 0xb3, 0xc2, 0x78,
	0x0a, 0x61, 0xf3, 0xbe, 0xa7, 0x21, 0xeb, 0xfe, 0x98, 0x1d, 0x60, 0xfe, 0x1d, 0x42, 0x8d, 0xa9,
	0x09, 0x45, 0x0a, 0x13, 0x8d, 0x44, 0x45, 0xd5, 0x67, 0xf4, 0xe3, 0x51, 0xc3, 0xc8, 0x3b, 0x04,
	0x42, 0xd4, 0xbb, 0xc4, 0x56, 0x0e, 0x3e, 0x41, 0x0e, 0xf4, 0x5f, 0xec, 0x7e, 0xba, 0xdb, 0xd5,
	0xc8, 0xfe, 0x6e, 0x63, 0xfe, 0xa3, 0xd3, 0x27, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x05, 0x8f, 0x6d,
	0x3c, 0x01, 0x00, 0x00,
}
