#声明版本
version: "3"
#定义服务
services:
  #服务名称，能够在同一个网络内按照名称访问
  consul:
    #说明采用的镜像地址
    image: jettjia/consul:v2.9.1
    #镜像对外映射的端口
    ports:
      - "8500:8500"
  #服务名称，能够在同一个网络内按照名称访问
  jaeger:
    #说明采用的镜像地址
    image: jettjia/jaeger:v2.9.1
    #镜像对外映射的端口
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  #熔断看板
  hystrix-dashboard:
    #说明采用的镜像地址
    image: jettjia/hystrix-dashboard:v2.9.1
    #镜像对外映射的端口
    ports:
      - "9002:9002"
  #熔断看板
  prometheus:
    #说明采用的镜像地址
    image: jettjia/prometheus:v2.9.1
    user: root
    #把外部yml文件挂载到容器中
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  #熔断看板
  grafana:
    #说明采用的镜像地址
    image: jettjia/grafana:v2.9.1
    #镜像对外映射的端口
    ports:
      - "3000:3000"